name: example
description: 
version: 1.0.0
homepage: 
authors: 
  - Isaque Neves <insinfo2008@gmail.com> 

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  postgres: ^2.1.1 
  fluent_query_builder: 
    path: ../

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
