name: example
description: 
version: 1.0.0
homepage: 
authors: 
  - Isaque Neves <insinfo2008@gmail.com> 
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:  
  #galileo_postgres: ^3.0.0
  postgres: ^2.4.3 
  convert: ^3.0.1
  #postgres:
  #  git:
  #    url: https://github.com/isoos/postgresql-dart.git
  #    ref: encoding

  fluent_query_builder: 
    path: ../

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
