language: dart
sudo: required
dart:
  - stable
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
#set PGPASSWORD=s1sadm1n
#psql.exe -h 127.0.0.1 -U postgres -p 5434 -w -c "create database banco_teste;" on windows
#psql.exe -h 127.0.0.1 -U postgres -p 5434 -w -d banco_teste -c "CREATE TABLE public.pessoas ( id serial NOT NULL , nome varchar(255), telefone varchar(255) , cpf varchar(255) , CONSTRAINT pessoas_pkey PRIMARY KEY (id) );"
  - sudo cp ci/pg_hba.conf /etc/postgresql/9.6/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -c 'create database banco_teste;' -U postgres
  - psql -c 'create user sisadmin with createdb;' -U postgres
  - psql -c "alter user sisadmin with password 's1sadm1n';" -U postgres
  - psql -c 'grant all on database banco_teste to sisadmin;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sisadmin;' -U postgres -d banco_teste
  - psql -c 'create user darttrust with createdb;' -U postgres
  - psql -c 'grant all on database banco_teste to darttrust;' -U postgres
  - psql -c 'CREATE TABLE public.pessoas ( id serial NOT NULL , nome varchar(255), telefone varchar(255) , cpf varchar(255) , CONSTRAINT pessoas_pkey PRIMARY KEY (id) );' -U postgres -d banco_teste
  - psql -c "INSERT INTO pessoas (nome,telefone,cpf) VALUES ('Isaque Neves Sant Ana', '(22) 99701-5305', '54654');" -U postgres -d banco_teste
  - pub get
dart_task:
  - test: --run-skipped -r expanded -j 1
#  - dartfmt -w ./
#  - dartanalyzer: --fatal-infos --fatal-warnings .

#after_success: bash ci/after_script.sh
branches:
  only:
    - master
    

