name: fluent_query_builder
description: A dart library that allows you to execute SQL queries in the PostgreSQL database in a fluent way, is very easy to execute.
version: 1.0.0
# homepage: https://www.example.com
authors: 
  - Isaque Neves <insinfo2008@gmail.com> 

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  postgres: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
