name: fluent_query_builder
description: A dart library that allows you to execute SQL queries in the PostgreSQL database in a fluent way, is very easy to execute.
version: 1.1.8
homepage: https://github.com/insinfo/fluent_query_builder
authors: 
  - Isaque Neves <insinfo2008@gmail.com> 

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  postgres: '>=1.0.2 <2.3.0' #^1.0.2 
  logging: '>=0.11.3 <2.0.0'
  pool: '>=1.2.3 <2.0.0'
  mysql1: '>=0.17.0 <0.18.0'
  sqljocky5: '>=2.2.0 <2.5.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
