# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Dart
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:  
  # Not sure these are actually being passed down to rails, set them as the default in database.yml
  DB_HOST: localhost
  DB_USERNAME: sisadmin
  DB_PASSWORD: s1sadm1n    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        sdk: [2.12.4]

    

    steps:
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Create additional user
        run: |
          sudo -u postgres psql --command="CREATE USER sisadmin PASSWORD 's1sadm1n'" --command="\du"

      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
    
      - name: Run tests
        run: dart run test --concurrency 1  --chain-stack-traces
